version: 2

updates:
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "08:41"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: python
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
